### ISSUE TITLE
Feature Request: extra option to return default-language

### ISSUE THREAD

**Issue by smoebody** [alexsk/mongoose-intl#13]
Hi,

since *mongoose-i18n* is dead i choosed your plugin to handle my i18n. the approach is very similar, in fact i like yours even more due to the language-setter-methods.

one thing im struggling with is the return of only the default-language when specifying `{virtuals: true}`. I use this option to return a document with its ID:
```js
console.log(myDocument.toObject({ virtuals: true }));
{ 
  title: 'new awesome place',
  description: 'new awesome place description',
  modified: 2018-01-19T08:34:52.442Z,
  created: 2018-01-19T08:34:52.442Z,
  id: '5a61adac0e19d4002c1529a8',
}
```
without `{ virtuals: true }` i get all languages, unfortunately also without the ID field:
```js
console.log(myDocument.toObject());
{ 
  title: 'new awesome place',
  description: {
    en_GB: 'new awesome place description',
    de_DE: 'neue abgefahrene Beschreibung des Platzes'
  }, 
  modified: 2018-01-19T08:34:52.442Z,
  created: 2018-01-19T08:34:52.442Z
}
```
Is there a way to separate these two behaviors somehow, maybe by providing an option `{language: 'default'|'en_GB' }` or such?

**Comment by alexsk** [comment]
Sorry, I didn't get the idea of your question.
Can you provide the full document you have in the collection, and the expected result that you'd like to get.

Thank you

**Comment by smoebody** [comment]
Sorry for not making myself clear enough. Basically i want to retrieve my document with all languages and its *id* field.

Lets say this is my model:
```js

const mongoose = require('mongoose');
const intl = require('mongoose-intl');

const model = new mongoose.Schema({
  title: {
    type: String
  },
  description: {
    type: String,
    intl: true
  }
});

model.plugin(intl, {
  languages: ['en_GB', 'de_DE'],
  defaultLanguage: 'en_GB'
});

const myModel = mongoose.model('MyModel', model);
```
Now i can do the following to set the languages which is perfectly fine:
```js
const myDocument = myModel.create({
  title: 'new awesome place',
  description: {
    en_GB: 'new awesome place description',
    de_DE: 'neue abgefahrene Beschreibung des Platzes'
  }
});
```
What i want to have returned now is the following:
```js
{
  id:  '5a61adac0e19d4002c1529a8',
  title: 'new awesome place',
  description: {
    en_GB: 'new awesome place description',
    de_DE: 'neue abgefahrene Beschreibung des Platzes'
  }
}
```
But the *id*-field is a virtual field and therefore only built when i set the option `virtuals: true`. Unfortunately this removes all languages and only returns the default-language for the document.

I think it is better to have a different option than `virtuals: true` to reduce the language to the documents' default language.

**Comment by alexsk** [comment]
The plugin works such way because the 'simplified' view (a regular string instead of a lang object) is a virtual as well, the same as the `id` field.

It's possible to get the requested format by using Mongoose transformation of the resulting object. Please see the full example below:
```js
const mongoose = require('mongoose');
const intl = require('mongoose-intl');

const model = new mongoose.Schema({
  title: {
    type: String
  },
  description: {
    type: String,
    intl: true
  }
});

model.plugin(intl, {
  languages: ['en_GB', 'de_DE'],
  defaultLanguage: 'en_GB'
});

const myModel = mongoose.model('MyModel', model);

const myDocument = new myModel({
  title: 'new awesome place',
  description: {
    en_GB: 'new awesome place description',
    de_DE: 'neue abgefahrene Beschreibung des Platzes'
  }
});

console.log(myDocument.toObject());

// { title: 'new awesome place',
//   description: 
//    { de_DE: 'neue abgefahrene Beschreibung des Platzes',
//      en_GB: 'new awesome place description' },
//   _id: 5a63bf3cbc66d921b9542883 }


console.log(myDocument.toObject({ virtuals: true }));

// { title: 'new awesome place',
//   description: 'new awesome place description',
//   _id: 5a63bf634c87f821dc532cb8,
//   id: '5a63bf634c87f821dc532cb8' }


// Transformation can be added also to the output:

console.log(myDocument.toObject({ transform(doc, ret) { ret.id = ret._id; delete ret._id; } }));

// { title: 'new awesome place',
//   description: 
//    { de_DE: 'neue abgefahrene Beschreibung des Platzes',
//      en_GB: 'new awesome place description' },
//   id: 5a63c0c25ad34523a157b192 }


console.log(myDocument.toObject({ virtuals: true, transform(doc, ret) { delete ret._id; } }));

// { title: 'new awesome place',
//   description: 'new awesome place description',
//   id: '5a63c0f679745523c44b1d4d' }

```

**Comment by smoebody** [comment]
All right, thats a way to do it. I will look into it, thanks for the hint.
