### ISSUE TITLE
Mongoose 5 compatibility

### ISSUE THREAD

**Issue by yelworc** [alexsk/mongoose-intl#15]
Is this library fully compatible with [Mongoose 5](https://github.com/Automattic/mongoose/wiki/5.0-Deprecation-Warnings) (and if so, could you update the peer dependency config in `package.json` accordingly)?

Tests in my project using `mongoose-intl` suggest that everything is fine after upgrading from 4 to 5 (apart from the npm peer dependency warning), but [this fork](https://github.com/bobsingor/mongoose-intl/commits/master) by @bobsingor has at least one Mongoose 5-specific change – I might just not be using specific features that cause problems.

**Comment by alexsk** [comment]
The fork you're referring to is based on `mongoose-intl v2.x` which already had some issues with Mongoose v4, and it's not fully compatible with `mongoose-intl v3.x` now.
Mongoose v5 was added to the peer dependencies alongside with v4.
`mongoose-intl v3.1.0` was published.

**Comment by yelworc** [comment]
Awesome, thank you!
