### ISSUE TITLE
Replace string with intl field for old docs.

### ISSUE THREAD

**Issue by ulikus** [alexsk/mongoose-intl#3]
Have multiple schema where field "name" and others was an ordinary string.
if i try to save it as intl field i get:
[MongoError: cannot use the part (name of name.en) to traverse the element ({name: "name"})].

**Comment by marcusforsberg** [comment]
I'm looking to add multi language support to an existing application and I'm worried I'll run into this type of issue since there are already a lot of existing strings in my data. Is there any way around this?

**Comment by alexsk** [comment]
Plugin enabling changes the schema structure. If you're updating the model for already existing data, than you need to make sure the data is updated accordingly. It's not a task for the plugin to update your database.

E.g. if you have a doc:
```js
{
  ...
  name: "Some title"
}
```
it should be converted to:
```js
{
  ...
  name: {
    en: "Some title"
  }
}
```
To be able to work without error in Mongoose.
It can be achieved by a simple migration script:
```js
db.collection.find().forEach(function (doc) {
  doc.name = { en: doc.name };
  db.collection.save(doc);
})
```
