### ISSUE TITLE
Cast to string failed for value error

### ISSUE THREAD

**Issue by ajmas** [alexsk/mongoose-intl#30]
Running into the issue:

{ CastError: Cast to string failed for value "{ en: 'Discord Admins', fr: 'Administrateurs Discord' }" at path "name"

Using in a Typescript based project.

In my schema:

```
import mongoose from 'mongoose';
import 'mongoose-intl';

const GroupSchema = new mongoose.Schema({
    key: {
        type: String,
        required: true,
        unique: true
    },
    name: {
        type: String,
        required: true,
        unique: true,
        intl: true
    }
}, {
    timestamps: true
});
```

and in my database loading file:

```
import mongoose from 'mongoose';
import mongooseIntl from 'mongoose-intl';

async function initDatabase() {
    mongoose.Promise = Promise;
    mongoose.plugin(mongooseIntl, { languages: ['en', 'fr'], defaultLanguage: 'en' });

    const connection = await mongoose.connect(dbUrl, {
        keepAlive: true,
        useNewUrlParser: true,
        useCreateIndex: true,
        useFindAndModify: false,
        useUnifiedTopology: true
    });

    return connection;
}

export default initDatabase;
```

Any ideas?

 - node: 10.15.3
 - mongoose: 5.7.11
 - mongoose-intl: 3.1.1

**Comment by Chrisimir** [comment]
I think you need to require Promise if you are going to use it like that
`Promise = require('promise')`
Not sure if it is leading to your error, but worth a shot.

**Comment by antoniopacheco** [comment]
I have the same issue when trying to set directly in to all schemas via
`mongoose.plugin(....`
but it works if you manually apply it to the individual schemas.
I guess this library needs an update?

**Comment by ajmas** [comment]
Applying it directly does indeed work, and this is the approach I have been using since after I opened the ticket. 

The mongoose [documentation](https://mongoosejs.com/docs/plugins.html) does indeed show this is right way of registering the plugin globally, suggesting something is misbehaving in the mongoose-intl.

BTW Promise is a global function in recent versions of NodeJS and `console.log(Promise)` outputs `[Function: Promise]`, as means of confirmation.

**Comment by antoniopacheco** [comment]
@ajmas i was able to make it work in my project.
My issue was that I was I porting my schemas before initiating that mongoose configuration

**Comment by antoniopacheco** [comment]
Where are you importing or defining your schemas ?

**Comment by ajmas** [comment]
@antoniopacheco I just tested this with one of my projects and confirm that it does indeed resolve the issue. makes sense really.

**In summary:** if we wish the plugin to be used globally, we need to ensure it is registered before creating the schemas, otherwise it will never be called.

With this I'll close the issue.
