### ISSUE TITLE
Support of Mongoose 6 and later

### ISSUE THREAD

**Issue by Genginzu** [alexsk/mongoose-intl#38]
Hello,

Coud someone tell us if this package is always supported and if an update is in progress to support mongoose 6 and later ?

Thank you in advance.

**Comment by ajmas** [comment]
Upgrading my mongoose version breaks my project to this:

```
npm ERR! Found: mongoose@6.0.14
npm ERR! node_modules/mongoose
npm ERR!   mongoose@"^6.0.14" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer mongoose@"~4 || ~5" from mongoose-intl@3.2.0
npm ERR! node_modules/mongoose-intl
npm ERR!   mongoose-intl@"3.2.0" from the root project
```

Does anyone know what API changes in mongoose 6 might break this?

**Comment by alexsk** [comment]
Duplicates #37
