### ISSUE TITLE
support for findAndUpdate and update queries?

### ISSUE THREAD

**Issue by linusbrolin** [alexsk/mongoose-intl#5]
I'm using findAndUpdate queries everywhere in my app.
Specifically .findByIdAndUpdate(), and sometimes pure .update() commands.
However, these do not seem to work with mongoose-intl.
It will simply overwrite the field (for example: title) completely with whatever I send in, completely ignoring any other existing translations.

For example:
```
var mongoose = require('mongoose');
var mongooseIntl = require('mongoose-intl');

var BlogPost = new mongoose.Schema({
    _id: String,
    title: { type: String, intl: true }
});
BlogPost.plugin(mongooseIntl, { languages: ['en', 'fr'], defaultLanguage: 'en' });
var BlogPostModel = mongoose.model('Post', BlogPost);

BlogPostModel.setDefaultLanguage('en');
var testen = new BlogPostModel({_id: 'test', title: 'test en'});
BlogPostModel
  .findByIdAndUpdate(testen._id, testen, { upsert: true, setDefaultsOnInsert: false, new: true })
  .exec(function(err, post_en) {
    // object contains the english title, seems about right so far...
    console.dir(post_en.get('title.all')); // { en: 'test en' }

    BlogPostModel.setDefaultLanguage('fr');
    let testfr = new BlogPostModel({_id: 'test', title: 'test fr'});
    BlogPostModel
      .findByIdAndUpdate(testfr._id, testfr, { upsert: true, setDefaultsOnInsert: false, new: true })
      .exec(function(err, post_fr) {
        // no english title included here? seems strange...
        console.dir(post_fr.get('title.all')); // { fr: 'test fr' }

        // let's search the db for the entire document and see if we can get the english title aswell
        BlogPostModel.findById('test').exec(function(err, post2) {
          // no english title found at all! It's been overwritten with the french title... :(
          console.dir(post2.get('title.all')); // { fr: 'test fr' }
        });
      });
  });
```

**Comment by alexsk** [comment]
Maybe the example is not accurate enough to explain the difficulties you have faced. But based on it I can say that everything works as expected here. You're creating a new document with the same id and with another title, and of course it overwrites the previous doc.
Here are my small code changes to show how to extend existing doc with the tile on another language:
```js
var mongoose = require('mongoose');
var mongooseIntl = require('mongoose-intl');

var BlogPost = new mongoose.Schema({
    _id: String,
    title: { type: String, intl: true }
});
BlogPost.plugin(mongooseIntl, { languages: ['en', 'fr'], defaultLanguage: 'en' });
var BlogPostModel = mongoose.model('Post', BlogPost);

BlogPostModel.setDefaultLanguage('en');
var testen = new BlogPostModel({_id: 'test', title: 'test en'});
BlogPostModel
    .findByIdAndUpdate(testen._id, testen, { upsert: true, setDefaultsOnInsert: false, 'new': true })
    .exec(function(err, post_en) {
        // object contains the english title, seems about right so far...
        console.dir(post_en.get('title.all')); // { en: 'test en' }

        /********************** CHANGES START **********************/
        // BlogPostModel.setDefaultLanguage('fr');
        // let testfr = new BlogPostModel({_id: 'test', title: 'test fr'});
        var testfr = post_en;
        testfr.setLanguage('fr');
        testfr.title = 'test fr'; // extend the post with the french title
        /********************** CHANGES END ************************/
        BlogPostModel
            .findByIdAndUpdate(testfr._id, testfr, { upsert: true, setDefaultsOnInsert: false, 'new': true })
            .exec(function(err, post_fr) {
                // no english title included here? seems strange...
                console.dir(post_fr.get('title.all')); // { fr: 'test fr' }

                // let's search the db for the entire document and see if we can get the english title aswell
                BlogPostModel.findById('test').exec(function(err, post2) {
                    // no english title found at all! It's been overwritten with the french title... :(
                    console.dir(post2.get('title.all')); // { fr: 'test fr' }
                });
            });
    });
```
And it will return expected `{ en: 'test en', fr: 'test fr' }` result.

**Comment by linusbrolin** [comment]
Alright, I see what you mean.
However, let's say the english save and french save are done by two different users on two different days.
When they load the document, they only load the language they are interested in, so when the document is then returned to the server for saving, it will still only contain the language they were interested in.

The problem with that is that I then have to first load the entire document (on the server, in order to get all available translations for all available fields), and then set the language wanted, then change the field wanted, then save.
That messes up the entire purpose of the "findAndUpdate" method.

The purpose of the "findAndUpdate" method is to update only the fields that are sent in, and leave the rest as-is.
Now I know that technically the title field (in the example) is the same field and if one translation is "missing" from what is sent in, then technically mongodb is doing the right thing by overwriting it entirely.
But, if I have to first load the entire document (to get all languages) everytime I want to update _one_ language, then as I said, the whole purpose of the "update" methods become moot.

What you should do in the plugin, is make sure that the "update" methods only update the selected language in the selected fields, and leave the rest as-is.

Edit:
To further explain how the "findAndUpdate" methods work (without the intl plugin).
Create a doc and save it:
```
var testen = new BlogPostModel({_id: 'test', title: 'test en', comment: 'testtest'});
BlogPostModel.findByIdAndUpdate(testen._id, testen, { upsert: true, setDefaultsOnInsert: false, 'new': true }).exec();
```
Create a new doc with the same id, but skip the comment field, and save it:
```
var testfr = new BlogPostModel({_id: 'test', title: 'test fr'});
BlogPostModel.findByIdAndUpdate(testfr._id, testfr, { upsert: true, setDefaultsOnInsert: false, 'new': true }).exec();
```
This will then produce the following:
`{ _id: 'test', title: 'test fr', comment: 'testtest' }`

This is the expected behaviour.
And this is why I expect any language that I have _not_ specifically specified to be overwritten to be left alone.

So _with_ the intl plugin active on the title field, I would expect it to behave like this:
Create a doc and save it:
```
var testen = new BlogPostModel({_id: 'test', title: 'test en', comment: 'testtest'});
testen.setLanguage('en');
BlogPostModel.findByIdAndUpdate(testen._id, testen, { upsert: true, setDefaultsOnInsert: false, 'new': true }).exec();
```
Should produce the following:
`{ _id: 'test', title: { en: 'test en' }, comment: 'testtest' }`

Create a new doc with the same id, but skip the comment field, and save it:
```
var testfr = new BlogPostModel({_id: 'test', title: 'test fr'});
testfr.setLanguage('fr');
BlogPostModel.findByIdAndUpdate(testfr._id, testfr, { upsert: true, setDefaultsOnInsert: false, 'new': true }).exec();
```
Should produce the following:
`{ _id: 'test', title: { en: 'test en', fr: 'test fr' }, comment: 'testtest' }`

**Comment by alexsk** [comment]
I see what you mean, but unfortunately the example with `comment` field will not work for the embedded documents, and all languages are stored as embedded documents.
`$set` operator (which is used underneath the `findByIdAndUpdate` method call) used with the embedded document will overwrite the entire sub-document.
It will not work the way you described even without the plugin. Please take a look:
```js
var BlogPost = new mongoose.Schema({
    _id: String,
    title: {
        en: String,
        fr: String
    },
    comment: String
});
var BlogPostModel = mongoose.model('Post', BlogPost);

var testen = new BlogPostModel({_id: 'test', title: { en: 'test en' }, comment: 'testtest'});
BlogPostModel.findByIdAndUpdate(testen._id, testen, { upsert: true, setDefaultsOnInsert: false, 'new': true }).exec();

// Produces the following MongoDB request:
// posts.findAndModify({ _id: 'test' }, [], {
//     '$setOnInsert': { __v: 0 },
//     '$set': { title: { en: 'test en' }, comment: 'testtest', _id: 'test' }
// }, {
//     upsert: true,
//     setDefaultsOnInsert: false,
//     new: true,
//     remove: false,
//     fields: {}
// });
// and the result document:
// { "_id" : "test", "__v" : 0, "title" : { "en" : "test en" }, "comment" : "testtest" }

var testfr = new BlogPostModel({_id: 'test', title: { fr: 'test fr' }});
BlogPostModel.findByIdAndUpdate(testfr._id, testfr, { upsert: true, setDefaultsOnInsert: false, 'new': true }).exec();

// MongoDB request for the 2nd document:
// posts.findAndModify({ _id: 'test' }, [], {
//     '$setOnInsert': { __v: 0 },
//     '$set': { title: { fr: 'test fr' }, _id: 'test' }
// }, {
//     upsert: true,
//     setDefaultsOnInsert: false,
//     new: true,
//     remove: false,
//     fields: {}
// });
// and the result document with the overwritten languages sub-document:
// { "_id" : "test", "__v" : 0, "title" : { "fr" : "test fr" }, "comment" : "testtest" }
```

This how Mongoose constructs mongo queries and how they are interpreted by MondoDB.
I can't see anything to be changed here at the plugin level.
