### ISSUE TITLE
Setting mongooseIntl globally does not appear to work with mongoose v4.9.6

### ISSUE THREAD

**Issue by yaro90** [alexsk/mongoose-intl#6]
Hi,

Thanks for the plugin.
Setting mongooseIntl globally does not appear to work with mongoose v4.9.6 while doing it directly to the schema works fine.

This works:
`BlogPost.plugin(mongooseIntl, { languages: ['en', 'de', 'fr'], defaultLanguage: 'en' });`

This does not work:
`mongoose.plugin(mongooseIntl, { languages: ['en', 'de', 'fr'], defaultLanguage: 'en' });`

Regards,
Yaro

**Comment by yaro90** [comment]
Looks like its not the issue with mongoose-intl, but a problem with mongoose v4.9.6 itself. Upgrading to mongoose v4.9.8 solved the issue.

**Comment by alexsk** [comment]
Thank you for posting the update here.
