### ISSUE TITLE
virtuals seem to break this plugin

### ISSUE THREAD

**Issue by smxsm** [alexsk/mongoose-intl#7]
Hi there, I have encountered a strange issue, if I enable virtuals for my mongoose schema, the intl part isn't working anymore, e.g. if I have a schema with an intl title field, everything works until I define a virtual field and set "virtuals: true" for toJSON:

`
  title: {
    type: String,
    required: true,
    intl: true
  }
...
OptionsSchema.set('toJSON', {
    virtuals: true
});
`

then only "title" is available, but not "title.en" e.g. any more ... can you verify that?
Thanks! :)

**Comment by alexsk** [comment]
That's the expected behavior described in the documentation: https://github.com/alexsk/mongoose-intl#returning-the-whole-document
If you still need both virtuals and full language schema — try to use `toObject()` method.

**Comment by smxsm** [comment]
Ah, sorry, didn't recognize that - thanks for the hint!
